name: Unit Test seed = "QED"

on:
  push:
    branches:
      - elifriedman

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: |
        git fetch
        git checkout elifriedman
      
    
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'adopt'


    - name: Install Dependencies
      run: mvn --batch-mode --update-snapshots package
      
    - name: JavaMake
      run: ./generate_jar.sh && ./simulate.sh
