name: Unit Test seed = "QED"

on:
  push:
    branches:
      - elifriedman

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: elifriedman
    
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'adopt'


    - name: Install Dependencies
      run: |
        cd cloudfed
        ./generate_jar.sh
        cd ../
      
    - name: JavaRun
      run: ./simulate.sh
